#!/bin/bash

ES_HOST=${ES_HOST:-localhost}
ES_NAME=${ES_NAME:-elasticsearch}
ES_T_PORT=${ES_T_PORT:-9300}
NAMENODE=${NAMENODE:-localhost}
ZOOKEEPER_HOSTS=${ZOOKEEPER_HOSTS:-localhost}

docker run -it --rm \
  -e ES_HOST=$ES_HOST \
  -e ES_NAME=$ES_NAME \
  -e ES_T_PORT=$ES_T_PORT \
  -e NAMENODE=$NAME_NODE \
  -e ZOOKEEPER_HOSTS=$ZOOKEEPER_HOSTS \
  predictionio:latest $@
