#!/bin/bash

ES_HOST=${ES_HOST:-localhost}
ES_NAME=${ES_NAME:-elasticsearch}
ES_T_PORT=${ES_T_PORT:-9300}
NAMENODE=${NAMENODE:-localhost}
ZOOKEEPER_HOSTS=${ZOOKEEPER_HOSTS:-localhost}
SPARK_MASTER=${SPARK_MASTER:-local}
SPARK_IMAGE=${SPARK_MASTER:-predictionio:latest}

docker run -it --rm \
  -e ES_HOST=$ES_HOST \
  -e ES_NAME=$ES_NAME \
  -e ES_T_PORT=$ES_T_PORT \
  -e NAMENODE=$NAME_NODE \
  -e ZOOKEEPER_HOSTS=$ZOOKEEPER_HOSTS \
  -e SPARK_MASTER=$SPARK_MASTER \
  -e SPARK_IMAGE=$SPARK_IMAGE \
  --entrypoint '/scripts/setup-env-pio-shell.sh' \
  predictionio:latest $@
